version: 2.1

orbs:
  rancher: ware2go/rancher@0.5.68

jobs:
  build:
    docker:
      - image: circleci/python:3.7

    working_directory: ~/repo

    steps:
      - checkout
      - setup_remote_docker
      - build:
          command: |
            if [ "${CIRCLE_TAG}" != "" ]; then
              IMAGE_NAME=$CIRCLE_PROJECT_REPONAME:$CIRCLE_TAG
              docker login -u $DOCKER_USER -p $DOCKER_PASS
              docker build -t $DOCKER_USER/$IMAGE_NAME .
              docker push $DOCKER_USER/$IMAGE_NAME
            fi
  deploy:
    docker:
      - image: circleci/python:3.7

    steps:
      - deploy:
          command: |
          if [ "${CIRCLE_BRANCH}" == "master" ]; then
            rancher 
          fi

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
