version: 2.1

orbs:
  slack: circleci/slack@3.4.2

jobs:
  build:
    docker:
      - image: circleci/python:3.7

    working_directory: ~/repo

    steps:
      - checkout
      - run: |
          echo "export COMMIT_MESSAGE=\"$(git log --format=%B -n 1 $CIRCLE_SHA1)\"" >> $BASH_ENV
          echo "export SHORT_GIT_HASH=\"$(echo $CIRCLE_SHA1 | cut -c -7)\"" >> $BASH_ENV
      - slack/notify:
          message: "Starting Build\n*Author* $CIRCLE_USERNAME\n*Branch* $CIRCLE_BRANCH\n*Commit* <https://github.com/PrimeCodingSolutions/otree-core/commit/$CIRCLE_SHA1|$SHORT_GIT_HASH>\n>$COMMIT_MESSAGE"
      - setup_remote_docker
      - run: |
          IMAGE_NAME=$CIRCLE_PROJECT_REPONAME:$CIRCLE_SHA1
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker build -t $DOCKER_USER/$IMAGE_NAME .
          if [[ "${CIRCLE_BRANCH}" == "master" || "${CIRCLE_BRANCH}" == "production" ]]; then
            docker push $DOCKER_USER/$IMAGE_NAME
          fi
      - slack/status:
          success_message: "Build :white_check_mark:\n*Author* $CIRCLE_USERNAME\n*Branch* $CIRCLE_BRANCH\n*Commit* <https://github.com/PrimeCodingSolutions/otree-core/commit/$CIRCLE_SHA1|$SHORT_GIT_HASH>\n>$COMMIT_MESSAGE"
          failure_message: "Build :x:\n*Author* $CIRCLE_USERNAME\n*Branch* $CIRCLE_BRANCH\n*Commit* <https://github.com/PrimeCodingSolutions/otree-core/commit/$CIRCLE_SHA1|$SHORT_GIT_HASH>\n>$COMMIT_MESSAGE"

  deploy:
    docker:
      - image: circleci/python:3.7
    parameters:
      domain:
        type: string
    steps:
      - checkout
      - run: |
          wget https://releases.rancher.com/cli/v0.6.14/rancher-linux-amd64-v0.6.14.tar.gz
      - run: |
          mkdir ~/lib && \
          sudo tar -xzvf rancher-linux-amd64-v0.6.14.tar.gz -C /usr/local/lib && \
          sudo ln -s /usr/local/lib/rancher-v0.6.14/rancher /usr/local/bin/rancher
      - run: |
          export SUBDOMAIN=<< parameters.domain >> && \
          export TAG=$CIRCLE_SHA1 && \
          rancher up \
          --stack << parameters.domain >> \
          --force-upgrade \
          --confirm-upgrade \
          --pull -d
      - run: |
          echo "export COMMIT_MESSAGE=\"$(git log --format=%B -n 1 $CIRCLE_SHA1)\"" >> $BASH_ENV
          echo "export SHORT_GIT_HASH=\"$(echo $CIRCLE_SHA1 | cut -c -7)\"" >> $BASH_ENV
      - slack/status:
          success_message: "Deploy :white_check_mark:\n*Author* $CIRCLE_USERNAME\n*Branch* $CIRCLE_BRANCH\n*Commit* <https://github.com/PrimeCodingSolutions/otree-core/commit/$CIRCLE_SHA1|$SHORT_GIT_HASH>\n>$COMMIT_MESSAGE"
          failure_message: "Deploy :x:\n*Author* $CIRCLE_USERNAME\n*Branch* $CIRCLE_BRANCH\n*Commit* <https://github.com/PrimeCodingSolutions/otree-core/commit/$CIRCLE_SHA1|$SHORT_GIT_HASH>\n>$COMMIT_MESSAGE"

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          name: "deploy_to_staging"
          requires:
            - build
          filters:
            branches:
              only:
                - master
          domain: staging
      - deploy:
          name: "deploy_to_production"
          requires:
            - build
          filters:
            branches:
              only:
                - production
          domain: production
